title: metasfresh documentation
name: metasfresh documentation
email: mail@metasfresh.com
url: "https://docs.metasfresh.org/"


collections:
  tests_collection:
    output: true
  howto_collection:
    output: true
  support_collection:
    output: true
  developers_collection:
    output: true
  webui_collection:
    output: true
  installation_collection:
    output: true
  jasper_reports_collection:
    output: true
  glossary_collection:
    output: true
  appdictionary_collection:
    output: true
  verticals_collection:
    output: true
  sql_collection:
    output: true
  setup:
    output: true
  talend_collection:
    output: true
  rest_api_collection:
    output: true
  contributors_guide_collection:
    output: true

defaults:
  - scope:
      path: ""
      type: tests
    values:
      layout: default
