name: metasfresh documentation
baseurl: /metasfresh-documentation

collections:
  tests_collection:
    output: true
  howto_collection:
    output: true
  support_collection:
    output: true
    incl_root: support

defaults:
  - scope:
      path: ""
      type: tests
    values:
      layout: default
