# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: metasfresh documentation
name: metasfresh documentation
email: mail@metasfresh.com
description: "We do Open Source ERP! Welcome to the official metasfresh documentation. WebUI User and Developer Guides, Support and Troubleshooting - all in one place!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.metasfresh.org"
fullurl: "https://docs.metasfresh.org"
twitter_username: metasfresh
github_username: metasfresh


collections:
  tests_collection:
    output: true
  howto_collection:
    output: true
  support_collection:
    output: true
  developers_collection:
    output: true
  webui_collection:
    output: true
  installation_collection:
    output: true
  intellij_collection:
    output: true
  jasper_reports_collection:
    output: true
  glossary_collection:
    output: true
  appdictionary_collection:
    output: true
  verticals_collection:
    output: true
  sql_collection:
    output: true
  setup:
    output: true
  talend_collection:
    output: true
  rest_api_collection:
    output: true
  contributors_guide_collection:
    output: true

defaults:
  - scope:
      path: ""
      type: tests
    values:
      layout: default
