name: metasfresh documentation
baseurl: /

collections:
  tests_collection:
    output: true
  howto_collection:
    output: true
  support_collection:
    output: true
  developers_collection:
    output: true
 
defaults:
  - scope:
      path: ""
      type: tests
    values:
      layout: default
